package sop_corba;


/**
* sop_corba/_SolucionStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 22 de mayo de 2018 07:24:34 AM COT
*/

public class _SolucionStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.Solucion
{

  public void establecerArquitectura (sop_corba.arquitecturaHolder objArquitectura)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("establecerArquitectura", true);
                $in = _invoke ($out);
                objArquitectura.value = sop_corba.arquitecturaHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                establecerArquitectura (objArquitectura        );
            } finally {
                _releaseReply ($in);
            }
  } // establecerArquitectura

  public sop_corba.fichero[] listarArchivosDuplicados (String rutaDirectorio)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarArchivosDuplicados", true);
                $out.write_string (rutaDirectorio);
                $in = _invoke ($out);
                sop_corba.fichero $result[] = sop_corba.SolucionPackage.listaFicherosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarArchivosDuplicados (rutaDirectorio        );
            } finally {
                _releaseReply ($in);
            }
  } // listarArchivosDuplicados

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/Solucion:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _SolucionStub
