package sop_corba;


/**
* sop_corba/arquitectura.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 22 de mayo de 2018 07:24:34 AM COT
*/

public final class arquitectura implements org.omg.CORBA.portable.IDLEntity
{
  public String nombreSistemaOperativo = null;
  public String arquitectura = null;
  public String version = null;
  public String separador = null;

  public arquitectura ()
  {
  } // ctor

  public arquitectura (String _nombreSistemaOperativo, String _arquitectura, String _version, String _separador)
  {
    nombreSistemaOperativo = _nombreSistemaOperativo;
    arquitectura = _arquitectura;
    version = _version;
    separador = _separador;
  } // ctor

} // class arquitectura
