package sop_corba;

/**
* sop_corba/ficheroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 22 de mayo de 2018 07:24:34 AM COT
*/

public final class ficheroHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.fichero value = null;

  public ficheroHolder ()
  {
  }

  public ficheroHolder (sop_corba.fichero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ficheroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ficheroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ficheroHelper.type ();
  }

}
