package sop_corba;


/**
* sop_corba/fichero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 22 de mayo de 2018 07:24:34 AM COT
*/

public final class fichero implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public boolean esArchivo = false;

  public fichero ()
  {
  } // ctor

  public fichero (String _nombre, boolean _esArchivo)
  {
    nombre = _nombre;
    esArchivo = _esArchivo;
  } // ctor

} // class fichero
