package sop_corba;


/**
* sop_corba/Solucion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 22 de mayo de 2018 07:24:34 AM COT
*/

public interface Solucion extends SolucionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Solucion
