package sop_corba.SolucionPackage;


/**
* sop_corba/SolucionPackage/listaFicherosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 22 de mayo de 2018 07:24:34 AM COT
*/

public final class listaFicherosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.fichero value[] = null;

  public listaFicherosHolder ()
  {
  }

  public listaFicherosHolder (sop_corba.fichero[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.SolucionPackage.listaFicherosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.SolucionPackage.listaFicherosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.SolucionPackage.listaFicherosHelper.type ();
  }

}
